//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHubModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport : Activity
    {
        public int PreferredNumberOfPlayers { get; set; }
        public int RequiredNumberOfPlayers { get; set; }
    }
}
