//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Sport
    {
        public int PreferredNumberOfPlayers { get; set; }
        public int RequiredNumberOfPlayers { get; set; }
        public int ActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
