//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    { 
        public Activity()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int ActivityId { get; set; }
        public string Name { get; set; }
        public string DayOfWeek { get; set; }
        public System.DateTime Time { get; set; }
        public int LocationId { get; set; }
        public bool Active { get; set; }
        public int PreferredNumberOfPlayers1 { get; set; }
        public int RequiredNumberOfPlayers1 { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual Location Location { get; set; }
    }
}
