//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Body { get; set; }
        public int UserId { get; set; }
        public int EventId { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
