//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
            this.PlusOnes = new HashSet<PlusOne>();
            this.Events = new HashSet<Event>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string EMail { get; set; }
        public bool IsAdmin { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<PlusOne> PlusOnes { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
